image: registry.cn-shenzhen.aliyuncs.com/packer-devops/docker:robot

stages:
- build
- deploy

before_script:
- docker login --username=$HUB_USER --password=$HUB_PASSWORD $HUB_DOMAIN

deploy_dev:
  stage: deploy
  script:
    - echo "测试环境打包静态资源.."
    - ssh root@$DEPLOY_DEV_SERVER_BASE "cd /root/app/frontend/abc_smart_code &&
      git pull"
  only:
    - dev

deploy_prod:
  stage: deploy
  script:
    - echo "正式环境打包静态资源.."
    - ssh root@$DEPLOY_PROD_SERVER_BALANCE "cd /app/abc_smart_code &&
      git pull"
  only:
    - master

